version: "3"
services:
  nginx:
    build: images/nginx
    command: nginx -g "daemon off;"
    links:
      - php
    ports:
      - "80:80"

  php:
    build: images/php
    volumes:
      - ./images/php:/var/www/html
    working_dir: /var/www/html/app/public
    command: php-fpm
    links:
      - db
      - cache
    ports:
      - "9000:9000"
    environment:
      APP_ENV: local
      APP_DEBUG: 'true'
      APP_KEY: SomeRandomKey!!!
      APP_LOCALE: en
      APP_FALLBACK_LOCALE: en
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_DATABASE: app
      DB_USERNAME: root
      DB_PASSWORD: root
      MEMCACHED_HOST: cache
      CACHE_DRIVER: memcached

  db:
    image: mysql:5.7
    ports:
      - "6000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - appnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "7000:80"
    links:
      - db:db
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - database:/var/lib/mysql
    networks:
      - appnet

  cache:
    image: memcached

volumes:
  database:

networks:
  appnet: